### ISSUE TITLE
"TransferWindowManager.h"에 struct SoccerTeam관련질문드립니다.

### ISSUE THREAD

**Issue by byoung-min** [developer0hye/2019_Kwangwoon_Univ_CE_DS_Project_1#4]
"TransferWindowManager.h"에 struct SoccerTeam에 SoccerTeam();
SoccerTeam(SoccerPlayerData fw, SoccerPlayerData mf, SoccerPlayerData df, SoccerPlayerData gk);
생성자가 두개 있고, 
.cpp에서는 SoccerTeam best_team; 주어졌길래 이거를 가지고 best_team 정보들을 넣어주었는데 
SoccerTeam(SoccerPlayerData fw, SoccerPlayerData mf, SoccerPlayerData df, SoccerPlayerData gk); 이것은 사용할 일이 없는데 사용해야하나요? 모든 주어진 스켈레톤 코드를 다 사용해야 한다 해서요

**Comment by developer0hye** [comment]
사용하지 않아도 괜찮습니다.
